package com.api.nutri.model.enuns;

public enum GrupoAlimentos {
	CEREAIS_DERIVADOS, VERDURAS_HORTALICAS_DERIVADOS, FRUTA_DERIVADOS, GORDURAS_OLEOS, PESCADOS_FRUTOSMAR,
	CARNES_DERIVADOS, LEITE_DERIVADOS, BEBIDAS, OVOS_DERIVADOS, PRODUDOS_AÇUCARADOS, MISCELANEAS, INDUSTRIALIZADO,
	ALIMENTOS_PREPARADOS, LEGUMINOSAS_DERIVADOS, NOZES_SEMEMTES;
}