package br.nutri.model.enuns;

public enum TecnicasCoccao {
	CONDUCAO, CONVENCAO, GRELHAR, GUISAR, BRASEAR, SALTEAR, CALOR_SECO, CALOR_UMIDO, CALOR_COMBINADO, FRITAR, REFOGAR,
	RADIACAO, SEMCOCCAO;
}
