package br.siguan.model.enuns;

public enum TipoInsumo {
	CEREAIS, VERDURAS_HORTALICAS, FRUTAS, GORDURAS_OLEOS, PESCADOS_FRUTOSMAR, CARNES_AVE, CARNES_SUINA, CARNE_VERMELHA,
	LEITE, BEBIDAS, POLPAS, OVO, PRODUTOS_ACUCARADOS, MISCELANEAS, INDUSTRIALIZADO, LEGUMINOSAS, NOZES_SEMENTES;
}